# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-09-14 19:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=6)),
                ('entry', models.DateTimeField(default=datetime.datetime(2019, 9, 15, 0, 42, 2, 933471))),
                ('exit', models.DateTimeField(default=datetime.datetime(2019, 9, 15, 0, 42, 2, 933471))),
            ],
        ),
        migrations.CreateModel(
            name='Registered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=6)),
            ],
        ),
    ]
