# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-09-14 19:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='flag',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='guest',
            name='entry',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 0, 57, 10, 504182)),
        ),
        migrations.AlterField(
            model_name='guest',
            name='exit',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 0, 57, 10, 504182)),
        ),
    ]
